name: publish

on:
  push:
    branches: [ master ]

jobs:
  sdist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup python3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Resetting git to master
        run: git reset --hard master

      - name: Resetting git to master
        run: git fetch --tags || true

      - name: Install poetry
        run: python -m pip install poetry

      - name: Install requirements
        run: poetry install

      - name: Publishing to pypi
        run: poetry publish --build --skip-existing --no-interaction
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_TOKEN }}
